#Jekyll configuration
name: Practical Prompt Engineering
description: The goal of this project is to combine all info about prompt engineering for AI art in a one useful document
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
